export type Archetype = {
  id: string;
  dossierId: string;
  name: string;
  gender: 'M' | 'F';
  archetype: string;
  tagline: string;
  quote: string;
  bio: string;
  vibe: string;
  energy: string;
  style: string;
  background: string;
  imageGradient: string;
  accentColor: string;
  // 5-dim personality vector:
  // [intensity, warmth, intellect, street, dominance]
  // each 0.0–1.0
  vector: [number, number, number, number, number];
};

export const archetypes: Archetype[] = [
  // ── MEN ──
  {
    id: 'jaxon',
    dossierId: '#011',
    name: 'Jaxon',
    gender: 'M',
    archetype: 'The Street Kingpin',
    tagline: 'Loyalty ain\'t given. It\'s earned.',
    quote: '"You want protection? You got it. You want honesty? Every time. You want sweet nothings? Wrong dossier."',
    bio: 'Five years upstate forged Jaxon into something the streets never expected — a man with both scars and a code. He runs deep, loves harder, and trusts slower than most. Leather and gold chains, hood lights at midnight.',
    vibe: 'Raw, Loyal, Protective',
    energy: 'Gritty / Guarded',
    style: 'Leather, Gold Chains',
    background: 'Street-raised, served time, built himself back',
    imageGradient: 'linear-gradient(180deg, #1a1410 0%, #0d0b08 60%, #000 100%)',
    accentColor: '#8b6914',
    vector: [0.9, 0.6, 0.3, 1.0, 0.85],
  },
  {
    id: 'malik',
    dossierId: '#007',
    name: 'Malik',
    gender: 'M',
    archetype: 'The Tech Mogul',
    tagline: 'Built different. Codes different.',
    quote: '"I don\'t just think outside the box. I architect a better one."',
    bio: 'Stanford dropout turned nine-figure founder. Malik speaks in patterns — market patterns, relationship patterns, legacy patterns. Quiet power in Yeezy and a mechanical keyboard.',
    vibe: 'Visionary, Quiet Power',
    energy: 'Cerebral / Composed',
    style: 'Minimal Luxury',
    background: 'Self-made, Bay Area tech scene',
    imageGradient: 'linear-gradient(180deg, #111418 0%, #08090d 60%, #000 100%)',
    accentColor: '#2a3a5a',
    vector: [0.6, 0.5, 0.95, 0.3, 0.7],
  },
  {
    id: 'isaiah',
    dossierId: '#002',
    name: 'Isaiah',
    gender: 'M',
    archetype: 'The Scholar',
    tagline: 'He reads Fanon in the morning. Baldwin at night.',
    quote: '"Knowledge without love is just information. I\'m interested in wisdom."',
    bio: 'PhD candidate. Spoken word poet. The kind of man who listens with his whole body. Isaiah moves slow, loves deliberate, and will quote Audre Lorde to you on a first date.',
    vibe: 'Thoughtful, Precise, Deep',
    energy: 'Gentle / Intentional',
    style: 'Wire rims, linen, bookmarks',
    background: 'Academic, activist, south side Chicago roots',
    imageGradient: 'linear-gradient(180deg, #121416 0%, #090a0c 60%, #000 100%)',
    accentColor: '#1a2a3a',
    vector: [0.4, 0.8, 1.0, 0.2, 0.35],
  },
  {
    id: 'marcus',
    dossierId: '#009',
    name: 'Marcus',
    gender: 'M',
    archetype: 'The Griot',
    tagline: 'Every story he tells will haunt you.',
    quote: '"Ancestors built us a language. I\'m just keeping it warm."',
    bio: 'Marcus holds the stories of four generations in his chest. Community organizer by day, storyteller by fire-circle. He cooks from memory, loves from memory, heals from memory.',
    vibe: 'Ancestral, Warm, Rooted',
    energy: 'Expansive / Present',
    style: 'Kente details, natural hair',
    background: 'New Orleans born, diaspora consciousness',
    imageGradient: 'linear-gradient(180deg, #161210 0%, #0c0a08 60%, #000 100%)',
    accentColor: '#5a3a10',
    vector: [0.5, 1.0, 0.75, 0.4, 0.3],
  },
  {
    id: 'devonte',
    dossierId: '#005',
    name: 'Devonte',
    gender: 'M',
    archetype: 'The Athlete',
    tagline: 'Discipline is a love language.',
    quote: '"I train the way I love. No shortcuts. No days off."',
    bio: 'Former NFL linebacker turned wellness entrepreneur. Devonte carries 240 pounds of intentionality. Early mornings, cold plunges, and flowers delivered on random Tuesdays.',
    vibe: 'Disciplined, Tender, Present',
    energy: 'Physical / Focused',
    style: 'Compression fits, fresh Jordans',
    background: 'Alabama-raised, pro sports, now rebuilding community gyms',
    imageGradient: 'linear-gradient(180deg, #121814 0%, #090d0a 60%, #000 100%)',
    accentColor: '#1a4a2a',
    vector: [0.8, 0.7, 0.4, 0.55, 0.75],
  },
  {
    id: 'ezra',
    dossierId: '#003',
    name: 'Ezra',
    gender: 'M',
    archetype: 'The Preacher\'s Son',
    tagline: 'Knew the hymns before he knew his own name.',
    quote: '"Church taught me structure. Life taught me grace. She\'ll teach me the rest."',
    bio: 'Ezra carries the weight of the pulpit and the freedom of the prodigal. He knows scripture and Coltrane equally. Spiritual but not rigid. Faithful but not naive.',
    vibe: 'Spiritual, Complex, Faithful',
    energy: 'Soulful / Conflicted',
    style: 'Sunday best meets Friday night',
    background: 'Pentecostal upbringing, questions he\'s still sitting with',
    imageGradient: 'linear-gradient(180deg, #141210 0%, #0b0a08 60%, #000 100%)',
    accentColor: '#3a2a10',
    vector: [0.55, 0.85, 0.7, 0.3, 0.4],
  },
  {
    id: 'roman',
    dossierId: '#008',
    name: 'Roman',
    gender: 'M',
    archetype: 'The Artist',
    tagline: 'He painted her portrait before they met.',
    quote: '"Everything I feel, I make. Everything I make, I give."',
    bio: 'Mixed-media artist and muralist. Roman sees the world in textures and tension. His hands are always stained with something — paint, clay, or purpose.',
    vibe: 'Creative, Sensitive, Intense',
    energy: 'Expressive / Searching',
    style: 'Paint-streaked denim, silver rings',
    background: 'Harlem-born, MFA grad, street murals that became galleries',
    imageGradient: 'linear-gradient(180deg, #181218 0%, #0d090d 60%, #000 100%)',
    accentColor: '#4a1a3a',
    vector: [0.7, 0.75, 0.65, 0.35, 0.4],
  },
  {
    id: 'jerome',
    dossierId: '#006',
    name: 'Jerome',
    gender: 'M',
    archetype: 'The Entrepreneur',
    tagline: 'Built three businesses. Learning to build himself.',
    quote: '"Success ain\'t the goal. Legacy is."',
    bio: 'Jerome has the spreadsheets, the portfolio, and the emptiness that comes with chasing the wrong things too long. Now he\'s learning to slow down without stopping.',
    vibe: 'Ambitious, Reflective, Growing',
    energy: 'Driven / Evolving',
    style: 'Tailored fits, no tie',
    background: 'Detroit-raised, serial founder, recently divorced',
    imageGradient: 'linear-gradient(180deg, #141610 0%, #0b0c08 60%, #000 100%)',
    accentColor: '#2a3a10',
    vector: [0.75, 0.55, 0.7, 0.45, 0.8],
  },
  {
    id: 'khalil',
    dossierId: '#001',
    name: 'Khalil',
    gender: 'M',
    archetype: 'The Healer',
    tagline: 'Therapist who forgot to heal himself.',
    quote: '"I hold space for everyone. Just learning to hold some for me."',
    bio: 'Licensed therapist. EMDR certified. Khalil has sat with the heaviest griefs in the city. He knows every trauma response except his own avoidance.',
    vibe: 'Empathic, Aware, Guarded',
    energy: 'Tender / Careful',
    style: 'Soft knits, reading glasses',
    background: 'Baltimore, trauma-informed care, yoga on weekends',
    imageGradient: 'linear-gradient(180deg, #101416 0%, #080c0e 60%, #000 100%)',
    accentColor: '#0a2a3a',
    vector: [0.35, 0.95, 0.85, 0.2, 0.25],
  },
  {
    id: 'tyrese',
    dossierId: '#010',
    name: 'Tyrese',
    gender: 'M',
    archetype: 'The Wildcard',
    tagline: 'Unpredictable in all the right ways.',
    quote: '"Life\'s too short for the expected. Let\'s do the thing we\'ll actually remember."',
    bio: 'Travel photographer. Part-time DJ. Full-time believer in spontaneous road trips. Tyrese has no five-year plan and is genuinely at peace with that.',
    vibe: 'Free, Playful, Magnetic',
    energy: 'Electric / Untameable',
    style: 'Vintage, statement pieces, always a camera',
    background: 'Miami raised, 40 countries visited, returns to his grandmother\'s every Christmas',
    imageGradient: 'linear-gradient(180deg, #181410 0%, #0d0b08 60%, #000 100%)',
    accentColor: '#5a3a10',
    vector: [0.85, 0.7, 0.5, 0.6, 0.55],
  },

  // ── WOMEN ──
  {
    id: 'deja',
    dossierId: '#010',
    name: 'Deja',
    gender: 'F',
    archetype: 'The Unfiltered Siren',
    tagline: 'She didn\'t come to be liked. She came to be felt.',
    quote: '"Baby I\'m loud, I\'m ratchet, I\'m from the ghetto — and every man I\'ve ever had has begged me not to change."',
    bio: 'Deja runs on frequency, not filter. 30-inch bundles, nails that could type a novel, and a laugh you\'ll hear from three floors up. She is the most real thing in any room.',
    vibe: 'Unapologetic, Loud, Iconic',
    energy: 'High-voltage / Fearless',
    style: 'Neon, long nails, bundles',
    background: 'East Atlanta, Section 8 to six figures, still has her momma\'s number on speed dial',
    imageGradient: 'linear-gradient(180deg, #1a1018 0%, #0f080d 60%, #000 100%)',
    accentColor: '#6a1a3a',
    vector: [1.0, 0.8, 0.4, 0.95, 0.75],
  },
  {
    id: 'imani',
    dossierId: '#004',
    name: 'Imani',
    gender: 'F',
    archetype: 'The Corporate Titan',
    tagline: 'She built the table. Didn\'t wait for a seat.',
    quote: '"Ambition isn\'t a personality flaw. It\'s a love language."',
    bio: 'Chief Strategy Officer at 34. Imani walks into rooms and changes their barometric pressure. She gives great advice, terrible vulnerability — she\'s working on it.',
    vibe: 'Sharp, Composed, Commanding',
    energy: 'Precise / Evolving',
    style: 'Power suits, no jewelry except one ring',
    background: 'DC-born, Howard grad, first in family to the C-suite',
    imageGradient: 'linear-gradient(180deg, #121418 0%, #090a0d 60%, #000 100%)',
    accentColor: '#1a2040',
    vector: [0.8, 0.5, 0.9, 0.25, 0.9],
  },
  {
    id: 'zora',
    dossierId: '#006',
    name: 'Zora',
    gender: 'F',
    archetype: 'The Neo-Soul',
    tagline: 'She vibrates at a frequency most can\'t tune into.',
    quote: '"I don\'t chase. I attract. The universe handles the logistics."',
    bio: 'Recording artist and sound healer. Zora smells like palo santo and late-night sessions. She\'ll read your natal chart before your first date and know your wounds before you name them.',
    vibe: 'Spiritual, Poetic, Magnetic',
    energy: 'Slow-burning / Mystical',
    style: 'Cowries, crochet, natural hair always free',
    background: 'Oakland roots, HBCU educated, three albums recorded in her living room',
    imageGradient: 'linear-gradient(180deg, #181218 0%, #0d090d 60%, #000 100%)',
    accentColor: '#4a1a5a',
    vector: [0.6, 0.9, 0.7, 0.3, 0.45],
  },
  {
    id: 'simone',
    dossierId: '#013',
    name: 'Simone',
    gender: 'F',
    archetype: 'The Diplomat',
    tagline: 'She negotiated peace treaties before breakfast.',
    quote: '"Conflict isn\'t the problem. Cowardice in conflict is."',
    bio: 'Foreign Service Officer. Fluent in four languages and the language of power. Simone has lived in seven countries and carries each one like a layer.',
    vibe: 'Measured, Worldly, Formidable',
    energy: 'Strategic / Warm underneath',
    style: 'Silk scarves, tailored, always a carry-on',
    background: 'Nigerian-American, Georgetown law, embassy circles worldwide',
    imageGradient: 'linear-gradient(180deg, #141618 0%, #0b0c10 60%, #000 100%)',
    accentColor: '#1a2a3a',
    vector: [0.65, 0.7, 0.95, 0.2, 0.8],
  },
  {
    id: 'nia',
    dossierId: '#015',
    name: 'Nia',
    gender: 'F',
    archetype: 'The Healer',
    tagline: 'She sees the wound before you show it.',
    quote: '"Healing isn\'t linear. And I\'m not going anywhere while you figure that out."',
    bio: 'Integrative medicine doctor and herbalist. Nia keeps a garden and a library with equal devotion. She believes in Western medicine and ancestral wisdom simultaneously.',
    vibe: 'Nurturing, Grounded, Sacred',
    energy: 'Still / Steady',
    style: 'Earthy tones, locs, no shoes inside',
    background: 'New Orleans, Tulane med school, treats the whole person',
    imageGradient: 'linear-gradient(180deg, #121814 0%, #090d0a 60%, #000 100%)',
    accentColor: '#1a4a20',
    vector: [0.35, 1.0, 0.8, 0.25, 0.3],
  },
  {
    id: 'aaliyah',
    dossierId: '#016',
    name: 'Aaliyah',
    gender: 'F',
    archetype: 'The Hustler',
    tagline: 'She built a brand from a kitchen table.',
    quote: '"Nobody handed me anything. Good. Now I know exactly how to hold it."',
    bio: 'CEO of her own beauty empire at 29. Aaliyah started with $200 and a YouTube channel. She\'s now in 3,000 Target stores and still personally responds to DMs.',
    vibe: 'Relentless, Self-made, Infectious',
    energy: 'Kinetic / Grounded',
    style: 'Her own brand head to toe',
    background: 'Memphis born, single mother\'s daughter, built without a blueprint',
    imageGradient: 'linear-gradient(180deg, #1a1410 0%, #0d0b08 60%, #000 100%)',
    accentColor: '#5a2a10',
    vector: [0.85, 0.65, 0.6, 0.7, 0.8],
  },
  {
    id: 'reign',
    dossierId: '#017',
    name: 'Reign',
    gender: 'F',
    archetype: 'The Athlete',
    tagline: 'Two Olympic medals. Zero apologies.',
    quote: '"People always ask how I stay motivated. I ask how they\'re comfortable standing still."',
    bio: 'Track and field legend turned sports psychologist. Reign trains bodies and the minds behind them. She is rigorous with herself and remarkably patient with everyone else.',
    vibe: 'Disciplined, Fierce, Loyal',
    energy: 'Explosive / Measured',
    style: 'Fitted training wear, no fuss, enormous presence',
    background: 'Houston, college phenom, two Olympics, now coaches champions',
    imageGradient: 'linear-gradient(180deg, #141810 0%, #0b0d08 60%, #000 100%)',
    accentColor: '#2a4a10',
    vector: [0.9, 0.65, 0.55, 0.5, 0.85],
  },
  {
    id: 'camille',
    dossierId: '#018',
    name: 'Camille',
    gender: 'F',
    archetype: 'The Bon Vivant',
    tagline: 'She turned pleasure into an art form.',
    quote: '"Joy is resistance. Especially for us. I take my resistance very seriously."',
    bio: 'Food critic, sommelier, travel writer. Camille has reviewed restaurants in 30 cities and still thinks her grandmother\'s kitchen wins. She tastes life slowly and completely.',
    vibe: 'Indulgent, Joyful, Sophisticated',
    energy: 'Sensual / Deliberate',
    style: 'Bold colors, big earrings, always a glass in hand',
    background: 'Louisiana Creole, Paris-educated palate, New York address',
    imageGradient: 'linear-gradient(180deg, #181410 0%, #0d0b08 60%, #000 100%)',
    accentColor: '#5a2a10',
    vector: [0.55, 0.85, 0.75, 0.3, 0.5],
  },
  {
    id: 'dominique',
    dossierId: '#019',
    name: 'Dominique',
    gender: 'F',
    archetype: 'The Strategist',
    tagline: 'She sees the endgame before you\'ve made your first move.',
    quote: '"I don\'t play chess to win. I play to understand my opponent."',
    bio: 'Political consultant who has run six campaigns. Dominique moves in rooms where decisions happen. She is two steps ahead in every relationship — personal or professional.',
    vibe: 'Calculated, Perceptive, Magnetic',
    energy: 'Controlled / Intense',
    style: 'Monochrome power looks, architectural jewelry',
    background: 'Philadelphia, Harvard Kennedy School, makes careers and occasionally ends them',
    imageGradient: 'linear-gradient(180deg, #161214 0%, #0d0a0b 60%, #000 100%)',
    accentColor: '#3a1a2a',
    vector: [0.75, 0.6, 0.95, 0.3, 0.95],
  },
  {
    id: 'phoenix',
    dossierId: '#020',
    name: 'Phoenix',
    gender: 'F',
    archetype: 'The Revolutionary',
    tagline: 'She burned down what didn\'t serve her people.',
    quote: '"Comfort was never the goal. Freedom is."',
    bio: 'Organizer, author, and unapologetic disruptor. Phoenix has been arrested four times for things she\'d do again. She loves with the same ferocity she fights.',
    vibe: 'Fierce, Principled, Tender in private',
    energy: 'Fire / Unwavering',
    style: 'Raised fist tees, combat boots, natural everything',
    background: 'Ferguson changed her. Everything she\'s done since has been on purpose.',
    imageGradient: 'linear-gradient(180deg, #1a1010 0%, #0d0808 60%, #000 100%)',
    accentColor: '#5a1010',
    vector: [1.0, 0.75, 0.85, 0.65, 0.9],
  },
];

// Pulse Quiz dimension labels
export const QUIZ_DIMENSIONS = [
  'intensity',   // 0 = calm, 1 = intense
  'warmth',      // 0 = cool/reserved, 1 = warm/nurturing
  'intellect',   // 0 = instinctive, 1 = cerebral
  'street',      // 0 = polished/refined, 1 = raw/street
  'dominance',   // 0 = soft/yielding, 1 = dominant/commanding
] as const;